import { color, font } from '@theme';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  headerText: {
    fontSize: 20,
    color: color.darkblue,
    fontFamily: font.urbanistBold,
    paddingHorizontal: 10,
  },
  headerContainer: {
    backgroundColor: color.white,
    padding: 20,
  },
  pizzaImage: { height: 150, width: 130, resizeMode: 'cover', borderRadius: 5 },
  pizzaNametext: {
    fontFamily: font.urbanistBold,
    fontSize: 18,
    color: color.darkblue,
  },
  pizzaDetailText: {
    fontFamily: font.urbanistSemiBold,
    fontSize: 12,
    width: '35%',
    color: color.darkblue,
  },
  card: {
    margin: 12,
    padding: 12,
    backgroundColor: color.white,
    borderRadius: 10,
    elevation: 3,
    position: 'relative',
  },
  title: {
    fontSize: 16,
    fontWeight: '700',
  },
  detail: {
    fontSize: 13,
    color: color.darGray,
    marginVertical: 6,
  },
  triggerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    backgroundColor: color.white,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: color.border,
    marginTop: 8,
  },
  triggerText: {
    fontSize: 14,
    fontWeight: '600',
    color: color.triggerText,
  },
  arrow: {
    fontSize: 20,
    marginLeft: 8,
    color: color.arrow,
  },
  popupWrapper: {
    position: 'absolute',
    zIndex: 1000,
    elevation: 10,
    alignSelf: 'center',
    marginLeft: 30,
  },
  arrowUp: {
    alignSelf: 'flex-end',
    marginLeft: 10,
    width: 0,
    height: 0,
    borderLeftWidth: 10,
    borderRightWidth: 10,
    borderBottomWidth: 12,
    borderStyle: 'solid',
    backgroundColor: 'transparent',
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: color.white,
    right: 15,
    marginTop: -20,
  },
  popupBox: {
    backgroundColor: color.white,
    borderRadius: 5,
    elevation: 5,
    minWidth: 200,
    padding: 10,
  },
  optionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 0.5,
    borderColor: color.border,
  },
  optionLabel: {
    fontSize: 14,
    fontFamily: font.urbanistSemiBold,
    color: color.triggerText,
  },
  optionPrice: {
    fontSize: 14,
    fontFamily: font.urbanistSemiBold,
    color: color.optionPrice,
  },
  backArrow: {
    height: 25,
    width: 25,
    resizeMode: 'contain',
    color: color.backArrow,
  },
  cartIcon: { height: 50, width: 50, resizeMode: 'contain' },
  cartIconContainer: {
    position: 'absolute',
    backgroundColor: color.primary,
    width: 20,
    height: 20,
    borderRadius: 10,
    right: 35,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cartText: { fontSize: 12, fontFamily: font.urbanistSemiBold },
  topTabContainer: {
    borderWidth: 1,
    borderRadius: 50,
    padding: 10,

    marginHorizontal: 3,
    borderColor: color.border,
  },
  topTabText: {
    fontSize: 14,
    fontFamily: font.urbanistSemiBold,
  },
  heartContainer: {
    position: 'absolute',
    bottom: 5,
    alignSelf: 'flex-end',
    padding: 5,
    backgroundColor: color.heartBackground,
    borderRadius: 50,
    right: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: color.heartIconBorder,
  },
  heartIcon: {
    height: 20,
    width: 20,
    resizeMode: 'contain',
    alignSelf: 'center',
    top: 1,
  },
  sizeContainer: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: color.border,
    marginTop: 7,
    alignItems: 'center',
    borderRadius: 10,
    width: 150,
    justifyContent: 'center',
  },
  pizzaSliceIcon: {
    height: 15,
    width: 15,
    resizeMode: 'cover',
  },
  addIcon: {
    height: 50,
    width: 50,
    marginTop: 7,
    marginLeft: 5,
  },
  backAndTitle: { flexDirection: 'row', alignItems: 'center' },
  headerSubContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  listContainer: { padding: 10 },
  directionRow: { flexDirection: 'row' },
  rightContainer: { marginLeft: 15 },
  textAndAdd: {
    flexDirection: 'row',
  },
  size: {
    marginLeft: 6,
    fontSize: 13,
    color: color.darkblue,
    maxWidth: 120,
    fontFamily: font.urbanistSemiBold,
  },
  paddingBottom: { paddingBottom: 150 },
  topBarView: { height: '10%', marginTop: 10 },
  horizontal: { marginHorizontal: 7 },
  alignSelf: { alignItems: 'center' },
  rightArrow: { height: 14, width: 14 },
  mainView: { flex: 1, backgroundColor: color.white },
  newText: { color: color.white, fontFamily: font.urbanistBold, fontSize: 12 },
  newContainer: {
    backgroundColor: color.red,
    position: 'absolute',
    right: 10,
    padding: 5,
    borderRadius: 2,
    top: 10,
    paddingHorizontal: 15,
  },
  topTabView: { flexDirection: 'row', paddingHorizontal: 3 },
  topTabIcon: { height: 21, width: 21, marginRight: 6 },
  moneyDisplayView: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '55%',
  },
});
