import { color, font } from '@theme';
import { StyleSheet } from 'react-native';

export const mealDealStyle = StyleSheet.create({
  headerSemiContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  arrowIcon: { height: 25, width: 25 },
  listContainer: {
    flexDirection: 'row',
    marginTop: 10,
    padding: 10,
    alignItems: 'center',
  },
  check: { height: 22, width: 22, tintColor: color.primary },
  uncheck: { height: 22, width: 22, tintColor: color.boxTint },
  mealsImage: {
    width: 50,
    height: 50,
    borderRadius: 5,
    marginLeft: 7,
    resizeMode: 'cover',
  },
  text: { fontSize: 16, fontFamily: font.urbanistSemiBold },
  subText: { fontSize: 13, fontFamily: font.urbanistMedium },
  bottomContainer: {
    position: 'absolute',
    bottom: 0,
    backgroundColor: color.white,
    width: '100%',
    padding: 15,
  },
  bottomTouch: {
    backgroundColor: color.primary,
    padding: 17,
    alignSelf: 'center',
    width: '90%',
    borderRadius: 3,
  },
  addToText: {
    color: color.white,
    alignSelf: 'center',
    fontSize: 16,
    fontFamily: font.urbanistSemiBold,
  },
  marginLeft: { marginLeft: 15 },
  marginBottom: { marginBottom: 80 },
  headerBack: {
    height: 195,
  },
  linearGradient: {
    height: '100%',
    padding: 16,
    justifyContent: 'center',
  },
  topDataContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  backTouch: {
    backgroundColor: color.slateGray,
    padding: 10,
    borderRadius: 50,
    borderWidth: 1,
    borderColor: color.slateGray,
    opacity: 0.5,
  },
  headerTitle: {
    color: color.white,
    fontSize: 20,
    marginLeft: 15,
    fontFamily: font.urbanistBold,
  },
  icon: { height: 20, width: 20, tintColor: color.white },
  titleContainer: {
    flexDirection: 'row',
    marginHorizontal: 15,
    marginTop: 15,
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  titleView: { flex: 1, paddingRight: 10, width: '50%' },
  title: { fontSize: 16, color: color.darkblue, fontFamily: font.urbanistBold },
  subtitle: {
    flexWrap: 'wrap',
    color: color.darkblue,
    fontSize: 12,
    fontFamily: font.urbanistMedium,
  },
  allergyTouch: {
    backgroundColor: color.allergyTouch,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  allergyText: {
    textAlign: 'center',
    textDecorationLine: 'underline',
    textDecorationColor: color.orange,
    color: color.orange,
    borderColor: color.orange,
    fontSize: 12,
    bottom: 2,
    fontFamily: font.urbanistSemiBold,
  },
  mainContainer: { flex: 1, backgroundColor: color.white },
  goBackView: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  alignSelf: { alignSelf: 'center' },
  flexGrow: { flexGrow: 1 },
});
