import { color, font } from '@theme';
import { StyleSheet } from 'react-native';

export const profileStyles = StyleSheet.create({
  profileImage: {
    height: 87,
    width: 87,
    resizeMode: 'contain',
    alignSelf: 'center',
    marginTop: 50,
  },
  editProfileText: {
    fontFamily: font.urbanistMedium,
    fontSize: 18,
    color: color.primary,
    alignSelf: 'center',
    marginTop: 10,
    borderBottomWidth: 1,
    borderColor: color.primary,
  },
  separator: {
    height: 1,
    backgroundColor: color.border,
    marginVertical: 6,
    marginHorizontal: 15,
    top: 15,
  },
  textInput: {
    borderWidth: 1,
    marginHorizontal: 15,
    marginTop: 40,
    height: 50,
    fontSize: 16,
    borderRadius: 5,
    borderColor: color.borderColor,
    padding: 15,
    fontFamily: font.urbanistBold,
  },
  yourNameView: {
    position: 'absolute',
    top: '30%',
    left: 30,
    padding: 3,
    backgroundColor: color.white,
    borderRadius: 2,
  },
  text: { fontFamily: font.urbanistRegular, color: color.editText },
  bottomContainer: {
    position: 'absolute',
    bottom: 0,
    backgroundColor: color.white,
    width: '100%',
    padding: 20,
    elevation: 50,
  },
  saveTouch: {
    backgroundColor: color.primary,
    padding: 15,
    alignSelf: 'center',
    width: '100%',
    borderRadius: 3,
  },
  saveText: {
    color: color.white,
    alignSelf: 'center',
    fontSize: 16,
    fontFamily: font.urbanistSemiBold,
  },
  dateContainer: {
    width: '92%',
    borderWidth: 1,
    marginHorizontal: 15,
    marginTop: 40,
    height: 50,
    borderRadius: 5,
    borderColor: color.borderColor,
    padding: 15,
    backgroundColor: color.white,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  dateLabel: {
    position: 'absolute',
    left: 10,
    padding: 3,
    backgroundColor: color.white,
    borderRadius: 2,
    top: -14,
  },
  dateIconView: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  dateIcon: { height: 24, width: 24, tintColor: color.slateGray },
  staticText: {
    fontFamily: font.urbanistRegular,
    fontSize: 13,
    color: color.staticText,
    marginLeft: 15,
  },
  dateTouchContainer: { flexDirection: 'row', alignItems: 'center' },
  mainView: { flex: 1, backgroundColor: color.white },
  DOB: {
    fontFamily: font.urbanistSemiBold,
    fontSize: 16,
    color: color.darkblue,
  },
});
