import imageIndex from '../../assets/imageIndex';

export const offerData = [
  {
    key: 1,
    offerText: 'GET MIN £125 OFF',
    freeText: '& Free Delivery',
    onYourOrder: 'on your order',
    image: imageIndex.mini,
    pizzaImage: imageIndex.miniPizzaA,
  },
  {
    key: 2,
    offerText: 'GET MIN £125 OFF',
    freeText: '& Free Delivery',
    onYourOrder: 'on your order',
    image: imageIndex.mini,
    pizzaImage: imageIndex.miniPizzaA,
  },
  {
    key: 3,
    offerText: 'GET MIN £125 OFF',
    freeText: '& Free Delivery',
    onYourOrder: 'on your order',
    image: imageIndex.mini,
    pizzaImage: imageIndex.miniPizzaA,
  },
];

export const dealsData = [
  {
    id: 1,
    image: imageIndex.dealsImage,
    text: 'Any 2 special chips',
    subText: 'Prize: £ 10.99',
    createDealsData: [
      {
        id: 28,
        image: imageIndex.pizzaPeace,
        title: 'Chips',
        text: 'Any 2 special chips',
        subText: 'You can choose any 2',
        price: '£ 10.99',
        cartID: 1,
        backImage: imageIndex.nachos,
        selectItem: 2,
        item: 1,
        isSelected: false,
        data: [
          {
            id: 48,
            image: imageIndex.nachos,
            text: 'Fully Loaded Cheese Mayo Chips',
            subText: 'Fully Loaded Cheese Mayo Chips',
            selected: false,
          },
          {
            id: 49,
            image: imageIndex.nachos,
            text: 'Peri Peri Cheese Mayo Chips',
            subText: 'Fully Loaded Cheese Mayo Chips',
            selected: false,
          },
          {
            id: 50,
            image: imageIndex.nachos,
            text: 'Spicy Cheese Mayo Chips',
            subText: 'Spicy Cheese Mayo Chips',
            selected: false,
          },
          {
            id: 51,
            image: imageIndex.nachos,
            text: 'Cheese and Corn',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 52,
            image: imageIndex.nachos,
            text: 'Ham and Pineapple',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
        ],
      },
    ],
  },
  {
    id: 2,
    image: imageIndex.dealsImage,
    text: 'Any 2 garlic bread',

    subText: 'Prize: £ 10.99',
    createDealsData: [
      {
        id: 29,
        image: imageIndex.pizzaPeace,
        text: 'Any 2 special Garlic bread',
        subText: 'You can choose any 2',
        title: 'Garlic bread',
        price: '£ 10.99',
        item: 1,

        cartID: 2,
        backImage: imageIndex.garlicBread,
        selectItem: 2,
        isSelected: false,
        data: [
          {
            id: 53,
            image: imageIndex.garlicBread,
            text: 'Garlic Bread',
            subText: '2 pieces of garlic bread',
            selected: false,
          },
          {
            id: 54,
            image: imageIndex.nachos,
            text: 'Garlic Bread',
            subText: '2 pieces of garlic bread',
            selected: false,
          },
          {
            id: 55,
            image: imageIndex.nachos,
            text: 'Garlic Bread',
            subText: '2 pieces of garlic bread',
            selected: false,
          },
        ],
      },
    ],
  },
  {
    id: 3,
    image: imageIndex.dealsImage,
    text: 'Home Alone',
    subText: 'Prize: £ 10.99',
    createDealsData: [
      {
        id: 30,
        image: imageIndex.pizzaPeace,
        text: 'Choose a pizza',
        subText: 'You can choose any 1 Pizzas',
        title: 'Pizza',
        price: '£ 10.99',
        cartID: 3,
        item: 3,

        backImage: imageIndex.pizzaA,
        selectItem: 1,
        isSelected: false,
        data: [
          {
            id: 56,
            image: imageIndex.pizzaA,
            text: 'Margherita 4',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 57,
            image: imageIndex.pizzaB,
            text: 'Cheese and Garlic',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 58,
            image: imageIndex.pizzaC,
            text: 'Double Cheese Margherita',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 59,
            image: imageIndex.pizzaA,
            text: 'Cheese and Corn',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 60,
            image: imageIndex.pizza,
            text: 'Ham and Pineapple',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 61,
            image: imageIndex.pizzaA,
            text: 'Double Cheese Margherita',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 62,
            image: imageIndex.pizzaA,
            text: 'Cheese and Corn',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 63,
            image: imageIndex.pizzaB,
            text: 'Ham and Pineapple',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 64,
            image: imageIndex.pizzaC,
            text: 'Double Cheese Margherita',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 65,
            image: imageIndex.pizzaA,
            text: 'Cheese and Corn',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
        ],
      },
      {
        id: 31,
        image: imageIndex.pizzaPeace,
        text: 'Choose a Garlic Bread ',
        subText: 'Choose any 1 Garlic Bread',
        title: 'Garlic bread',
        price: '£ 10.99',
        cartID: 3,
        item: 3,

        backImage: imageIndex.garlicBread,
        selectItem: 1,
        isSelected: false,
        data: [
          {
            id: 66,
            image: imageIndex.garlicBread,
            text: 'Garlic Bread',
            subText: '2 pieces of garlic bread',
            selected: false,
          },
          {
            id: 67,
            image: imageIndex.nachos,
            text: 'Garlic Bread',
            subText: '2 pieces of garlic bread',
            selected: false,
          },
          {
            id: 68,
            image: imageIndex.nachos,
            text: 'Garlic Bread',
            subText: '2 pieces of garlic bread',
            selected: false,
          },
        ],
      },
      {
        id: 32,
        image: imageIndex.bread,
        text: 'Choose a Drinks',
        subText: 'Choose any 1 Drinks',
        title: 'Drinks',
        backImage: imageIndex.cola,
        price: '£ 10.99',
        cartID: 3,
        item: 3,

        selectItem: 1,
        isSelected: false,
        data: [
          {
            id: 69,
            image: imageIndex.cola,
            text: 'Coca cola',
            subText: '',
            selected: false,
          },
          {
            id: 70,
            image: imageIndex.cola,
            text: 'Pepsi',
            subText: '',
            selected: false,
          },
          {
            id: 71,
            image: imageIndex.cola,
            text: 'Fanta',
            subText: '',
            selected: false,
          },
        ],
      },
    ],
  },
  {
    id: 4,
    image: imageIndex.dealsImage,
    text: 'Double Decker',
    subText: 'Prize: £ 10.99',
    createDealsData: [
      {
        id: 33,
        image: imageIndex.pizzaPeace,
        text: 'Choose a pizza',
        subText: 'You can choose any 1 Pizzas',
        title: 'Pizza',
        backImage: imageIndex.pizzaA,
        price: '£ 10.99',
        cartID: 4,
        item: 3,

        selectItem: 1,
        isSelected: false,
        data: [
          {
            id: 72,
            image: imageIndex.pizzaA,
            text: 'Margherita 4',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 73,
            image: imageIndex.pizzaB,
            text: 'Cheese and Garlic',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 74,
            image: imageIndex.pizzaC,
            text: 'Double Cheese Margherita',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 75,
            image: imageIndex.pizzaA,
            text: 'Cheese and Corn',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 76,
            image: imageIndex.pizza,
            text: 'Ham and Pineapple',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
        ],
      },
      {
        id: 34,
        image: imageIndex.pizzaPeace,
        text: 'Choose a Gustos Special Chips',
        subText: 'Choose 1 Gustos Special Chips',
        title: 'Chips',
        backImage: imageIndex.nachos,
        price: '£ 10.99',
        cartID: 4,
        item: 3,

        selectItem: 1,
        isSelected: false,
        data: [
          {
            id: 77,
            image: imageIndex.nachos,
            text: 'Fully Loaded Cheese Mayo Chips',
            subText: 'Fully Loaded Cheese Mayo Chips',
            selected: false,
          },
          {
            id: 78,
            image: imageIndex.nachos,
            text: 'Spicy Cheese Mayo Chips',
            subText: 'Fully Loaded Cheese Mayo Chips',
            selected: false,
          },
          {
            id: 79,
            image: imageIndex.nachos,
            text: 'Peri PeriCheese Mayo Chips',
            subText: 'Fully Loaded Cheese Mayo Chips',
            selected: false,
          },
        ],
      },
      {
        id: 35,
        image: imageIndex.bread,
        text: 'Choose a Drinks',
        subText: 'Choose any 1 Drinks',
        title: 'Drinks',
        backImage: imageIndex.cola,
        price: '£ 10.99',
        item: 3,

        cartID: 4,
        selectItem: 1,
        isSelected: false,
        data: [
          {
            id: 80,
            image: imageIndex.cola,
            text: 'Coca cola',
            subText: '',
            selected: false,
          },
          {
            id: 81,
            image: imageIndex.cola,
            text: 'Pepsi',
            subText: '',
            selected: false,
          },
          {
            id: 82,
            image: imageIndex.cola,
            text: 'Fanta',
            subText: '',
            selected: false,
          },
        ],
      },
    ],
  },
  {
    id: 5,
    image: imageIndex.dealsImage,
    text: 'Friendly Meal',
    subText: 'Prize: £ 10.99',
    createDealsData: [
      {
        id: 36,
        image: imageIndex.pizzaPeace,
        text: 'Choose a pizza',
        subText: 'You can choose any 1 Pizzas',
        title: 'Pizza',
        backImage: imageIndex.pizzaA,
        price: '£ 10.99',
        cartID: 5,
        item: 3,

        selectItem: 1,
        isSelected: false,
        data: [
          {
            id: 83,
            image: imageIndex.pizzaA,
            text: 'Margherita 4',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 84,
            image: imageIndex.pizzaB,
            text: 'Cheese and Garlic',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 85,
            image: imageIndex.pizzaC,
            text: 'Double Cheese Margherita',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 86,
            image: imageIndex.pizzaA,
            text: 'Cheese and Corn',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 87,
            image: imageIndex.pizza,
            text: 'Ham and Pineapple',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
        ],
      },
      {
        id: 37,
        image: imageIndex.pizzaPeace,
        text: 'Choose a Gustos Special Chips',
        subText: 'Choose 1 Gustos Special Chips',
        title: 'Chips',
        backImage: imageIndex.nachos,
        price: '£ 10.99',
        cartID: 5,
        item: 3,

        selectItem: 1,
        isSelected: false,
        data: [
          {
            id: 88,
            image: imageIndex.nachos,
            text: 'Fully Loaded Cheese Mayo Chips',
            subText: 'Fully Loaded Cheese Mayo Chips',
            selected: false,
          },
          {
            id: 89,
            image: imageIndex.nachos,
            text: 'Peri peru Cheese Mayo Chips',
            subText: 'Fully Loaded Cheese Mayo Chips',
            selected: false,
          },
          {
            id: 90,
            image: imageIndex.nachos,
            text: 'Spicy Cheese Mayo Chips',
            subText: 'Fully Loaded Cheese Mayo Chips',
            selected: false,
          },
        ],
      },
      {
        id: 38,
        image: imageIndex.bread,
        text: 'Choose a Drinks',
        subText: 'Choose any 1 Drinks',
        title: 'Drinks',
        backImage: imageIndex.cola,
        price: '£ 10.99',
        cartID: 5,
        item: 3,

        selectItem: 1,
        isSelected: false,
        data: [
          {
            id: 91,
            image: imageIndex.cola,
            text: 'Coca cola',
            subText: '',
            selected: false,
          },
          {
            id: 92,
            image: imageIndex.cola,
            text: 'Pepsi',
            subText: '',
            selected: false,
          },
          {
            id: 93,
            image: imageIndex.cola,
            text: 'Fanta',
            subText: '',
            selected: false,
          },
        ],
      },
    ],
  },
  {
    id: 6,
    image: imageIndex.dealsImage,
    text: 'Popper',
    subText: 'Prize: £ 10.99',
    createDealsData: [
      {
        id: 39,
        image: imageIndex.pizzaPeace,
        text: 'Choose a pizza',
        subText: 'You can choose any 1 Pizza',
        title: 'Pizza',
        backImage: imageIndex.pizzaA,
        cartID: 6,
        price: '£ 10.99',
        item: 4,

        selectItem: 1,
        isSelected: false,
        data: [
          {
            id: 94,
            image: imageIndex.pizzaA,
            text: 'Margherita 4',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 95,
            image: imageIndex.pizzaB,
            text: 'Cheese and Garlic',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 96,
            image: imageIndex.pizzaC,
            text: 'Double Cheese Margherita',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 97,
            image: imageIndex.pizzaA,
            text: 'Cheese and Corn',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
        ],
      },
      {
        id: 40,
        image: imageIndex.pizzaPeace,
        text: 'Choose a Gustos Special Chips',
        subText: 'Choose any 1 Gustos Special Chips',
        title: 'Chips',
        backImage: imageIndex.nachos,
        cartID: 6,
        price: '£ 10.99',
        selectItem: 1,
        item: 4,

        isSelected: false,
        data: [
          {
            id: 98,
            image: imageIndex.nachos,
            text: 'Peri Peri Mayo Chips',
            subText: 'Peri Peri Mayo Chips',
            selected: false,
          },
          {
            id: 99,
            image: imageIndex.nachos,
            text: 'Cheese Mayo Chips',
            subText: 'Cheese Mayo Chips',
            selected: false,
          },
          {
            id: 100,
            image: imageIndex.nachos,
            text: 'Spicy Mayo Chips',
            subText: 'Cheese Mayo Chips',
            selected: false,
          },
          {
            id: 101,
            image: imageIndex.nachos,
            text: 'Cheese and Corn',
            subText: 'Fully Loaded Cheese Mayo Chips',
            selected: false,
          },
          {
            id: 102,
            image: imageIndex.nachos,
            text: 'Fully Loaded Cheese Mayo Chips',
            subText: 'Fully Loaded Cheese Mayo Chips',
            selected: false,
          },
        ],
      },
      {
        id: 41,
        image: imageIndex.bread,
        text: 'Choose a Premium Garlic Bread',
        subText: 'Choose any 2 Premium Garlic Bread',
        title: 'Premium Garlic bread',
        backImage: imageIndex.garlicBread,
        price: '£ 10.99',
        cartID: 6,
        item: 4,

        selectItem: 2,
        isSelected: false,
        data: [
          {
            id: 108,
            image: imageIndex.garlicBread,
            text: 'Garlic Bread',
            subText: '2 Pieces of garlic bread',
            selected: false,
          },
          {
            id: 109,
            image: imageIndex.garlicBread,
            text: 'Cheese and Garlic',
            subText: '2 Pieces of garlic bread',
            selected: false,
          },
          {
            id: 110,
            image: imageIndex.garlicBread,
            text: 'Double Cheese Garlic Bread',
            subText: '2 Pieces of garlic bread',
            selected: false,
          },
        ],
      },
      {
        id: 42,
        image: imageIndex.fries,
        text: 'Choose a Drinks',
        subText: 'Please choose any 2 Drinks',
        title: 'Drinks',
        backImage: imageIndex.cola,
        price: '£ 10.99',
        cartID: 6,
        item: 4,

        selectItem: 2,
        isSelected: false,
        data: [
          {
            id: 111,
            image: imageIndex.cola,
            text: 'Coca cola',
            subText: '',
            selected: false,
          },
          {
            id: 112,
            image: imageIndex.cola,
            text: 'Pepsi',
            subText: '',
            selected: false,
          },
          {
            id: 113,
            image: imageIndex.cola,
            text: 'Fanta',
            subText: '',
            selected: false,
          },
          {
            id: 114,
            image: imageIndex.cola,
            text: 'Coca cola',
            subText: '',
            selected: false,
          },
        ],
      },
    ],
  },
  {
    id: 7,
    image: imageIndex.dealsImage,
    text: 'Mega Deal',
    subText: 'Prize: £ 10.99',
    createDealsData: [
      {
        id: 43,
        image: imageIndex.pizzaPeace,
        text: 'Choose a pizza 1',
        subText: 'You can choose any 2',
        title: 'Pizza',
        backImage: imageIndex.pizzaA,
        price: '£ 10.99',
        cartID: 7,
        item: 5,

        selectItem: 2,
        isSelected: false,
        data: [
          {
            id: 115,
            image: imageIndex.pizzaA,
            text: 'Margherita 4',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 116,
            image: imageIndex.pizzaB,
            text: 'Cheese and Garlic',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 117,
            image: imageIndex.pizzaC,
            text: 'Double Cheese Margherita',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 118,
            image: imageIndex.pizzaA,
            text: 'Cheese and Corn',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 119,
            image: imageIndex.pizza,
            text: 'Ham and Pineapple',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 120,
            image: imageIndex.pizzaA,
            text: 'Double Cheese Margherita',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 121,
            image: imageIndex.pizzaA,
            text: 'Cheese and Corn',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 122,
            image: imageIndex.pizzaB,
            text: 'Ham and Pineapple',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 123,
            image: imageIndex.pizzaC,
            text: 'Double Cheese Margherita',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 124,
            image: imageIndex.pizzaA,
            text: 'Cheese and Corn',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
        ],
      },
      {
        id: 44,
        image: imageIndex.pizzaPeace,
        text: 'Choose a pizza 2',
        subText: 'You can choose any 1',
        title: 'Pizza 2',
        backImage: imageIndex.pizzaA,
        price: '£ 10.99',
        cartID: 7,
        item: 5,

        selectItem: 1,
        isSelected: false,
        data: [
          {
            id: 125,
            image: imageIndex.pizzaA,
            text: 'Margherita 4',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 126,
            image: imageIndex.pizzaB,
            text: 'Cheese and Garlic',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 127,
            image: imageIndex.pizzaC,
            text: 'Double Cheese Margherita',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 128,
            image: imageIndex.pizzaA,
            text: 'Cheese and Corn',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 129,
            image: imageIndex.pizza,
            text: 'Ham and Pineapple',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 130,
            image: imageIndex.pizzaA,
            text: 'Double Cheese Margherita',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 131,
            image: imageIndex.pizzaA,
            text: 'Cheese and Corn',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 132,
            image: imageIndex.pizzaB,
            text: 'Ham and Pineapple',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 133,
            image: imageIndex.pizzaC,
            text: 'Double Cheese Margherita',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 134,
            image: imageIndex.pizzaA,
            text: 'Cheese and Corn',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
        ],
      },
      {
        id: 45,
        image: imageIndex.bread,
        text: 'Choose a garlic bread',
        subText: 'You can choose any 1',
        title: 'Garlic bread',
        backImage: imageIndex.garlicBread,
        price: '£ 10.99',
        cartID: 7,
        item: 5,

        selectItem: 1,
        isSelected: false,
        data: [
          {
            id: 135,
            image: imageIndex.garlicBread,
            text: 'Garlic Bread',
            subText: '2 pieces',
            selected: false,
          },
          {
            id: 136,
            image: imageIndex.garlicBread,
            text: 'Cheese and Garlic',
            subText: '2 pieces',
            selected: false,
          },
          {
            id: 137,
            image: imageIndex.garlicBread,
            text: 'Double Cheese Garlic Bread',
            subText: '2 pieces',
            selected: false,
          },
          {
            id: 138,
            image: imageIndex.garlicBread,
            text: 'Cheese and Corn',
            subText: '2 pieces',
            selected: false,
          },
        ],
      },
      {
        id: 46,
        image: imageIndex.fries,
        text: 'Choose a chips',
        subText: 'You can choose any 1',
        title: 'Chips',
        backImage: imageIndex.nachos,
        price: '£ 10.99',
        cartID: 7,
        item: 5,

        selectItem: 1,
        isSelected: false,
        data: [
          {
            id: 139,
            image: imageIndex.nachos,
            text: 'Peri Peri Mayo Chips',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 140,
            image: imageIndex.nachos,
            text: 'Cheese Mayo Chips',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 141,
            image: imageIndex.nachos,
            text: 'Spicy Mayo Chips',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 142,
            image: imageIndex.nachos,
            text: 'Fully Loaded Chips',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
          {
            id: 143,
            image: imageIndex.nachos,
            text: 'Spicy Tango',
            subText: 'Size: Extra Large (16 inches)',
            selected: false,
          },
        ],
      },
      {
        id: 47,
        image: imageIndex.cans,
        text: 'Choose a bottle of drinks',
        subText: 'You can choose any 2',
        title: 'Drinks',
        backImage: imageIndex.cola,
        price: '£ 10.99',
        cartID: 7,
        item: 5,
        selectItem: 2,
        isSelected: false,
        data: [
          {
            id: 144,
            image: imageIndex.cola,
            text: 'Coca cola',
            subText: '',
            selected: false,
          },
          {
            id: 145,
            image: imageIndex.cola,
            text: 'Pepsi',
            subText: '',
            selected: false,
          },
          {
            id: 146,
            image: imageIndex.cola,
            text: 'Fanta',
            subText: '',
            selected: false,
          },
        ],
      },
    ],
  },
];
