import { color, font } from '@theme';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  mainView: { flex: 1, backgroundColor: color.white },
  listContainer: {
    marginHorizontal: 15,
    marginTop: 40,
    borderColor: color.red,
    borderRadius: 5,
    flex: 1,
  },
  listContainerForBorder: {
    marginHorizontal: 15,
    marginTop: 40,
    borderColor: color.border,
    borderRadius: 5,
    borderWidth: 1,
  },
  listView: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    marginHorizontal: 10,
    marginTop: 10,
  },
  image: { height: 60, width: 60, marginRight: 10 },
  title: { fontSize: 16, fontFamily: font.urbanistBold },
  size: {
    fontSize: 12,
    color: color.darGray,
    fontFamily: font.urbanistSemiBold,
    width: 160,
  },
  priceView: { flexDirection: 'row', alignItems: 'center', marginTop: 10 },
  moneyIcon: { height: 15, width: 15 },
  priceText: {
    fontSize: 12,
    color: color.darGray,
    fontFamily: font.urbanistSemiBold,
    left: 5,
  },
  quantityView: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    paddingHorizontal: 7,
    borderColor: color.border,
    borderRadius: 5,
  },
  minusText: {
    color: color.black,
    fontSize: 28,
    paddingHorizontal: 5,
  },
  numberText: {
    fontSize: 16,
    minWidth: 20,
    textAlign: 'center',
    color: color.primary,
    fontFamily: font.urbanistBold,
  },
  add: {
    backgroundColor: color.primary,
    padding: 15,
    paddingHorizontal: 25,
    borderRadius: 3,
    marginLeft: 10,
  },
  addTipText: { color: color.white, fontFamily: font.urbanistMedium },
  plusText: {
    color: color.black,
    fontSize: 18,
    paddingHorizontal: 5,
  },
  separatorView: {
    height: 1,
    backgroundColor: color.border,
    marginHorizontal: 20,
  },
  compText: {
    fontSize: 20,
    fontFamily: font.urbanistBold,
    marginTop: 20,
    marginLeft: 15,
  },
  mealDataView: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    marginRight: 15,
    backgroundColor: color.white,
    padding: 10,
    borderRadius: 5,
    borderColor: color.border,
  },
  itemImage: {
    height: 50,
    width: 50,
    resizeMode: 'cover',
    borderRadius: 2,
  },
  marginLeft: { marginLeft: 10 },
  addIcon: {
    height: 28,
    width: 28,
    alignSelf: 'flex-end',
    resizeMode: 'contain',
    marginTop: 2,
    marginLeft: 5,
  },
  mealList: { marginHorizontal: 15, marginTop: 10 },
  addTouch: { alignSelf: 'flex-end' },
  listFooterTouch: {
    alignSelf: 'center',
    padding: 15,
    flexDirection: 'row',
    alignItems: 'center',
  },
  addMoreText: { fontSize: 16, fontFamily: font.urbanistSemiBold },
  swipeContainer: {
    backgroundColor: color.white,
    position: 'absolute',
    bottom: 0,
    width: '100%',
    alignItems: 'center',
    padding: 10,
    elevation: 50,
    opacity: 1,
  },
  railStyle: {
    marginHorizontal: 5,
    marginVertical: 5,
    borderRadius: 30,
    marginLeft: 5,
  },
  titleStyle: {
    fontFamily: font.urbanistMedium,
    paddingHorizontal: 20,
    textAlign: 'center',
    marginLeft: 15,
  },
  thumbView: {
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  thumbIcon: { height: 28, width: 28, resizeMode: 'contain' },
  nameView: { marginLeft: 15 },
  marginBottom: { marginBottom: 110 },
  megDealTextContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  tipView: {
    flexDirection: 'row',
    marginHorizontal: 15,
    marginTop: 10,
    alignItems: 'center',
  },
  inputView: {
    borderWidth: 1,
    borderRadius: 3,
    width: '70%',
    borderColor: color.border,
    padding: 4,
    flexDirection: 'row',
    alignItems: 'center',
  },
  MoneyIcon: {
    height: 20,
    width: 20,
    tintColor: color.slateGray,
    marginHorizontal: 10,
    opacity: 0.8,
  },
  tipInput: { fontSize: 14, width: '80%' },
  addNoteView: {
    marginHorizontal: 15,
    borderWidth: 1,
    borderRadius: 5,
    borderColor: color.border,
    marginTop: 30,
    padding: 5,
    backgroundColor: color.offWhite,
  },
  addNoteText: {
    position: 'absolute',
    top: -12,
    marginLeft: 15,
    backgroundColor: color.white,
    paddingHorizontal: 5,
  },
  totalView: {
    marginBottom: 120,
    borderWidth: 1,
    marginHorizontal: 15,
    marginTop: 30,
    borderColor: color.border,
    borderRadius: 5,
  },
  subTotalView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 15,
    paddingHorizontal: 20,
  },
  subTotalText: { fontSize: 14, fontFamily: font.urbanistSemiBold },
  totalText: { fontSize: 14, fontFamily: font.urbanistSemiBold },
  listEmptyView: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  validationImage: {
    height: 160,
    width: 215,
    resizeMode: 'cover',
    alignSelf: 'center',
  },
  text: {
    fontSize: 20,
    fontFamily: font.urbanistBold,
    alignSelf: 'center',
    marginTop: 15,
  },
  subText: {
    fontSize: 14,
    fontFamily: font.urbanistMedium,
    textAlign: 'center',
    marginTop: 10,
  },
  flexView: {
    flexGrow: 1,
  },
  editIcon: { height: 15, width: 15, resizeMode: 'cover' },
});
