import { color, font } from '@theme';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    marginTop: 20,
  },
  headerContainer: {
    backgroundColor: color.white,
    padding: 20,
  },
  deliveryText: {
    fontSize: 16,
    fontFamily: font.urbanistSemiBold,
    color: color.delivery,
  },
  add: {
    fontSize: 16,
    fontFamily: font.urbanistRegular,
    color: color.add,
    alignSelf: 'center',
    marginTop: 5,
  },
  headerText: {
    fontSize: 20,
    color: color.darkblue,
    fontFamily: font.urbanistBold,
    paddingHorizontal: 10,
  },
  linearGradient: {
    marginTop: 20,
    borderRadius: 8,
    padding: 15,
    alignItems: 'center',
  },
  menuContainer: {
    flex: 1,
  },
  dealImage: {
    resizeMode: 'contain',
    flex: 1,
    height: 167,
    width: '100%',
    padding: 10,
    marginTop: 15,
  },
  txtContainer: { position: 'absolute', top: 110, left: 30 },
  varietiesTxt: {
    color: color.varietiesText,
    fontSize: 13,
    fontFamily: font.urbanistSemiBold,
  },
  dealTxt: {
    fontSize: 25,
    fontFamily: font.spicyRiceRegular,
    color: color.dealText,
    fontWeight: '400',
  },
  homeIcon: {
    height: 20,
    width: 20,
    resizeMode: 'contain',
    alignSelf: 'center',
  },
  arrow: {
    height: 20,
    width: 20,
    resizeMode: 'contain',
    alignSelf: 'center',
  },
  addContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  mini: {
    height: 150,
    width: '95%',
    alignSelf: 'center',
    borderRadius: 5,
  },
  miniPizza: {
    height: 130,
    width: 130,
    marginTop: 20,
    borderRadius: 5,
    left: 22,
    resizeMode: 'cover',
  },
  groupOrderImage: {
    height: 150,
    width: '95%',
    alignSelf: 'center',
    borderRadius: 15,
  },

  offerText: {
    fontSize: 20,
    color: color.offerText,
    marginLeft: 10,
    marginTop: 25,
    fontFamily: font.urbanistBold,
  },
  headerIcon: { flexDirection: 'row', marginTop: 10 },
  groupOrderTextContainer: { position: 'absolute', top: 80, left: 30 },
  getOffText: {
    fontSize: 22,
    color: color.white,
    fontFamily: font.passionOneBold,
    marginTop: 5,
  },
  freeDeliveryText: {
    fontSize: 16,
    color: color.white,
    fontFamily: font.urbanistBold,
  },
  yourOrderText: {
    fontSize: 14,
    color: color.white,
    fontFamily: font.urbanistRegular,
  },
  orderNowContainer: {
    backgroundColor: color.white,
    borderRadius: 50,
    padding: 7,
    width: '70%',
    alignItems: 'center',
    marginTop: 10,
  },
  orderNowText: {
    fontSize: 16,
    color: color.orderNowText,
    fontFamily: font.passionOneRegular,
    fontWeight: '400',
  },
  marginTopTen: {
    marginTop: 10,
  },
  offerAndBenefitText: {
    position: 'absolute',
    top: '25%',
    left: 30,
  },
  offerAndBenefitContainer: {
    flex: 1,
  },
  removeText: {
    color: color.red,
    marginLeft: 20,
    fontFamily: font.urbanistBold,
    fontSize: 14,
  },
  removeTouch: { alignSelf: 'center' },
  offerBenefitText: {
    fontSize: 20,
    color: color.black,
    fontFamily: font.urbanistBold,
  },
  offerImage: {
    height: 150,
    width: 360,
  },
  appIntroPaginationContainer: {
    position: 'absolute',
    bottom: 15,
    alignSelf: 'center',
    backgroundColor: color.dotBackGround,
    padding: 10,
    borderRadius: 20,
    flexDirection: 'row',
  },
  appIntroPagination: {
    width: 8,
    height: 8,
    borderRadius: 6,
    marginHorizontal: 4,
  },
  imageStyle: {
    marginLeft: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: color.borderColor,
  },
  overLayTextMenu: {
    bottom: 10,
    position: 'absolute',
    marginLeft: 20,
  },
  offerAndBenefitIcon: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: '10%',
  },
  offerTitle: { fontSize: 20, fontFamily: font.urbanistBold },
  offerSubTitle: {
    fontSize: 13,
    fontFamily: font.urbanistSemiBold,
    color: color.subText,
  },
  whatsYourMindContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: 10,
    marginBottom: 15,
  },
  yourMindLabel: {
    fontFamily: font.urbanistBold,
    fontSize: 20,
    color: color.mindLabel,
  },
  viewAllText: { fontFamily: font.urbanistBold, color: color.primary },
  mindMenuContainer: {
    backgroundColor: color.white,
    padding: 5,
    marginHorizontal: 10,
    borderRadius: 5,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: color.borderColor,
  },
  mindMenuImage: {
    height: 75,
    width: 75,
    borderRadius: 3,
    resizeMode: 'contain',
  },
  mindText: {
    textAlign: 'center',
    fontFamily: font.urbanistBold,
    color: color.darkblue,
    fontSize: 12,
    padding: 7,
  },
  appIntraView: { height: '23%' },
  paddingTen: { padding: 10 },
  radius: { borderRadius: 5 },
  textViewContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 22,
    marginTop: 5,
  },
  marginTopFifteen: { marginTop: 15 },
  marginBottom: { marginBottom: 60 },
  flexGrow: {
    flexGrow: 1,
  },
  flex: {
    flex: 1,
    backgroundColor: color.white,
  },
  flexOne: { flex: 1 },
});
