import { color, font } from '@theme';
import { StyleSheet } from 'react-native';

export const style = StyleSheet.create({
  subHeader: { flexDirection: 'row' },
  label: {
    fontFamily: font.urbanistBold,
    fontSize: 18,
    color: color.darkblue,
    marginLeft: 15,
    marginTop: 30,
  },
  OrderPlaced: {
    fontFamily: font.urbanistBold,
    fontSize: 18,
    color: color.darkblue,
    marginLeft: 15,
    marginTop: 80,
  },
  rewardStep: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  stepContainer: {
    marginTop: 8,
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,

    justifyContent: 'center',
    alignItems: 'center',
  },
  tickText: { color: color.white, fontSize: 12, fontWeight: 'bold' },
  stepLine: {
    position: 'absolute',
    top: 70,
    height: 2,
    width: 110,
    left: 10,
  },
  cardContainer: {
    padding: 20,
    borderWidth: 1,
    marginTop: 10,
    borderColor: color.border,
    backgroundColor: color.white,
    borderRadius: 5,
  },
  upperContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 5,
  },
  orderIDText: { fontFamily: font.urbanistSemiBold, fontSize: 15 },
  addText: {
    fontFamily: font.urbanistMedium,
    fontSize: 13,
    color: color.subText,
  },
  rewardIcon: { height: 28, width: 28, resizeMode: 'contain' },
  separator: {
    height: 1,
    backgroundColor: color.backGround,
    marginTop: 10,
  },
  orderItemContainer: {
    flexDirection: 'row',
    marginTop: 10,
    alignItems: 'center',
  },
  itemImage: { height: 32, width: 32, borderRadius: 3, resizeMode: 'contain' },
  itemName: {
    fontFamily: font.urbanistBold,
    fontSize: 14,
    marginLeft: 10,
    color: color.subText,
  },
  cardBottomContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  date: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
    color: color.subText,
  },
  reOrderContainer: { flexDirection: 'row', alignItems: 'center' },
  reOrderIcon: {
    height: 16,
    width: 16,
    right: 5,
    resizeMode: 'contain',
    alignItems: 'center',
  },
  reOrderText: {
    fontFamily: font.urbanistBold,
    fontSize: 14,
    color: color.slateGray,
  },
  rewardIconA: { width: 40, height: 40, padding: 15 },
  rewardIconView: { alignItems: 'center', padding: 12 },
  listStyle: { marginHorizontal: 15 },

  popup: {
    backgroundColor: color.white,
    padding: 20,
    borderRadius: 12,
    width: '80%',
    alignItems: 'center',
    elevation: 6,
  },
  popupTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: color.primary,
    marginBottom: 8,
  },
  popupText: {
    fontSize: 14,
    color: color.darGray,
    marginBottom: 15,
    textAlign: 'center',
  },
  closeButton: {
    backgroundColor: color.primary,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
  },
  rewardLabel: {
    position: 'absolute',
    top: 90,
    width: 230,
    left: 9,
    backgroundColor: color.white,
    padding: 15,
    borderWidth: 1,
    borderColor: color.border,
    borderRadius: 5,
    justifyContent: 'center',
  },
  rewardLabelText: {
    fontSize: 12,
    fontWeight: '600',
    color: color.primary,
    marginTop: 4,
  },
  listFooter: {
    marginBottom: 20,
    flexDirection: 'row',
    alignSelf: 'center',
    marginTop: 25,
  },
  infoImage: { height: 20, width: 20, resizeMode: 'contain' },
  termsText: {
    fontSize: 14,
    color: color.subText,
    marginLeft: 5,
    borderBottomWidth: 1,
    borderStyle: 'dashed',
    borderColor: color.subText,
  },
  popUp: {
    alignSelf: 'flex-start',
    marginLeft: 10,
    width: 0,
    height: 0,
    borderLeftWidth: 10,
    borderRightWidth: 10,
    borderBottomWidth: 12,
    borderStyle: 'solid',
    backgroundColor: 'transparent',
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: color.white,
    right: 15,
    marginTop: -20,
  },
  orderText: { color: color.slateGray, fontSize: 12 },
  flex: { flex: 1 },
  flexGrow: { flexGrow: 1 },
});
