import { color, font } from '@theme';
import { StyleSheet } from 'react-native';

export const style = StyleSheet.create({
  cartContainer: {
    position: 'absolute',
    backgroundColor: color.primary,
    width: 20,
    height: 20,
    borderRadius: 10,
    right: 35,
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  cartIcon: { height: 50, width: 50, resizeMode: 'contain' },
  addToWishListCOntainer: {
    position: 'absolute',
    bottom: 5,
    alignSelf: 'flex-end',
    padding: 10,
    backgroundColor: color.heartBackground,
    borderRadius: 50,
    right: 5,
  },
  heartIcon: {
    height: 20,
    width: 20,
    resizeMode: 'contain',
  },
  itemImage: { height: 150, width: 130, resizeMode: 'cover', borderRadius: 5 },
  pizzaName: {
    fontSize: 18,
    fontFamily: font.urbanistBold,
    color: color.darkblue,
  },
  description: {
    fontSize: 12,
    width: '30%',
    fontFamily: font.urbanistMedium,
    color: color.darkblue,
  },
  touchContainer: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: color.border,
    padding: 4,
    marginTop: 7,
    alignItems: 'center',
    borderRadius: 10,
  },
  pizzaSliceIcon: {
    height: 20,
    width: 20,
    resizeMode: 'contain',
  },
  addIcon: {
    height: 50,
    width: 50,
    marginTop: 7,
  },
  leftArrowIcon: { height: 25, width: 25, resizeMode: 'contain' },
  marginTop: { marginTop: 25 },
  padding: { padding: 10 },
  directionRow: { flexDirection: 'row' },
  marginLeft: { marginLeft: 15 },
  sizeText: {
    marginLeft: 10,
    color: color.darkblue,
    fontFamily: font.urbanistSemiBold,
    width: 130,
  },
  listEmptyView: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: '50%',
  },
  validationIcon: {
    height: 160,
    width: 215,
    resizeMode: 'contain',
    alignSelf: 'center',
  },
  noDataFoundText: {
    alignSelf: 'center',
    fontSize: 18,
    color: color.darkblue,
    justifyContent: 'center',
    fontFamily: font.urbanistBold,
  },
  newText: { color: color.white, fontFamily: font.urbanistBold, fontSize: 12 },
  newContainer: {
    backgroundColor: color.red,
    position: 'absolute',
    right: 10,
    padding: 5,
    borderRadius: 2,
    top: 10,
    paddingHorizontal: 15,
  },
  priceContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
  },
  directionSize: { flexDirection: 'row', marginTop: 10 },
  mainContainer: { flex: 1, backgroundColor: color.white },
});
