import { color, font } from '@theme';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  headerContainer: {
    backgroundColor: color.white,
    padding: 20,
    shadowColor: color.black,
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
  },
  headerText: {
    fontSize: 20,
    color: color.darkblue,
    fontFamily: font.urbanistBold,
    marginTop: 10,
  },
  userProfileContainer: {
    flexDirection: 'row',
    padding: 15,
    alignItems: 'center',
    marginTop: 20,
  },
  userProfile: { height: 100, width: 100, resizeMode: 'cover' },
  userTextContainer: { marginLeft: 15, width: '50%' },
  userNameText: {
    fontSize: 20,
    fontFamily: font.urbanistSemiBold,
    color: color.darkblue,
  },
  userEmail: {
    fontSize: 13,
    fontFamily: font.urbanistMedium,
    marginTop: 5,
    color: color.darkblue,
  },
  orderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 15,
  },
  orderText: {
    fontSize: 13,
    fontFamily: font.urbanistSemiBold,
    color: color.blueGray,
    marginBottom: 2,
  },
  number: {
    fontSize: 20,
    fontFamily: font.urbanistSemiBold,
    color: color.blueGray,
  },
  separator: {
    width: 1,
    height: '100%',
    backgroundColor: color.backGround,
    marginHorizontal: 10,
  },
  topSeparator: {
    backgroundColor: color.backGround,
    height: 1,
    marginVertical: 6,
    marginHorizontal: 20,
  },
  rewardText: {
    fontSize: 13,
    fontFamily: font.urbanistSemiBold,
    color: color.blueGray,
  },
  label: {
    fontFamily: font.urbanistBold,
    fontSize: 14,
    marginLeft: 25,
    marginTop: 15,
    color: color.label,
  },
  gustoList: { borderWidth: 1, borderRadius: 15, borderColor: color.border },
  listText: {
    fontSize: 16,
    fontFamily: font.urbanistMedium,
    color: color.blueGray,
  },
  listSeparator: {
    height: 1,
    backgroundColor: color.border,
    marginVertical: 6,
  },
  accountContainer: {
    borderWidth: 1,
    borderRadius: 15,
    borderColor: color.border,
    marginHorizontal: 10,
    marginTop: 10,
    backgroundColor: color.offWhite,
    padding: 5,
    paddingVertical: 5,
  },
  accountSeparator: {
    height: 1,
    backgroundColor: color.border,
    marginVertical: 6,
  },
  touch: { flexDirection: 'row', justifyContent: 'space-between', padding: 15 },
  rightIcon: { height: 18, width: 18, alignSelf: 'center' },
  paddingTen: { padding: 10 },
  numView: { flexDirection: 'row', alignItems: 'flex-end' },
  mainContainer: { flex: 1, backgroundColor: color.white },
  legalCart: { backgroundColor: color.offWhite, padding: 2 },
  pizzaCard: { backgroundColor: color.offWhite, padding: 2 },
  flexGrow: { flexGrow: 1 },
});
